<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: vineri, 4 noiembrie 2022 10:11:53</msg><msg code="0" type="0">Se genereaza layerul comune</msg><msg code="0" type="0">Se genereaza layerul puncte</msg><msg code="0" type="0">Se genereaza layerul caiFerate</msg><msg code="0" type="0">Se selecteaza punctele dupa clauza COMUNE = 'Torino'</msg><msg code="0" type="0">Se selecteaza punctele de interes din comuna selectata</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\PuncteComune.py", line 82, in &lt;module&gt;
    sel_loc_dupa_drum(in_comune=comune,
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\PuncteComune.py", line 50, in sel_loc_dupa_drum
    arcpy.SelectLayerByAttribute_management(in_layer_or_view=drumuri_com,
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10780, in SelectLayerByAttribute
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10777, in SelectLayerByAttribute
    retval = convertArcObjectToPythonObject(gp.SelectLayerByAttribute_management(*gp_fixargs((in_layer_or_view, selection_type, where_clause, invert_where_clause), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000358: Invalid expression
Failed to execute (SelectLayerByAttribute).

</msg><msg code="0" type="0">Failed script (null)...</msg><msg code="-2147467259" type="100">Failed to execute (PuncteInComune).</msg><msg code="0" type="3">Failed at vineri, 4 noiembrie 2022 10:11:54 (Elapsed Time: 1,22 seconds)</msg></messages>